#pragma once
#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <regex>
#include <set>
#include <string>
#include <vector>

namespace fs = std::filesystem;

struct DefinitionLocation {
  std::string FilePath;
  int Line;
};

class GlobalsManager {
  std::set<std::string> StaticGlobals = {
      // Lua 5.0 - TODO check which of those really work in tg2
      "assert",
      "collectgarbage",
      "dofile",
      "error",
      "getfenv",
      "getmetatable",
      "ipairs",
      "load",
      "loadfile",
      "loadstring",
      "module",
      "next",
      "pairs",
      "pcall",
      "print",
      "rawequal",
      "rawget",
      "rawset",
      "require",
      "select",
      "setfenv",
      "setmetatable",
      "tonumber",
      "tostring",
      "type",
      "unpack",
      "xpcall",
      "string",
      "table",
      "math",
      "io",
      "os",
      "debug",
      "coroutine",
      "_G",
      "_VERSION",

      // GuildGameScriptBinding
      "SimFindProduction",
      "SquadCreate",
      "SquadGet",
      "SimFindSquad",
      "DynastyFindSquad",
      "SquadDestroy",
      "SquadAddRandom",
      "SquadGetProfession",
      "SquadGetMemberCount",
      "SquadGetVacantPlace",
      "SquadIsReady",
      "SquadSetReady",
      "SquadIsNeeded",
      "SquadAddMember",
      "SquadRemoveMember",
      "SquadGetLeader",
      "SquadGetLeaderId",
      "SquadGetMember",
      "SquadMemberExists",
      "SquadGetMeetingPlace",
      "SquadSetMeetingPlace",
      "SquadGetState",
      "SetArg",
      "OutputDebugString",
      "CMsgNews",
      "MsgQuick",
      "MsgMeasure",
      "MsgSystem",
      "CMsgSay",
      "ShowOverheadSymbol",
      "RemoveOverheadSymbol",
      "RemoveOverheadSymbols",
      "RemoveAllOverheadSymbols",
      "StartGameTimer",
      "CheckGameTimerEnd",
      "RemoveDialogBox",
      "SetCampaignEndText",
      "ScenarioGetObjectByName",
      "ScenarioGetKontorGoodCount",
      "ScenarioGetKontorGoodInfo",
      "ScenarioGetItemIdCount",
      "ScenarioGetItemIdByNumber",
      "ScenarioGetRandomObject",
      "ScenarioGetObjects",
      "ScenarioGetImperialCapitalId",
      "ScenarioGetImperialCapital",
      "ScenarioSetImperialCapital",
      "ScenarioCreateResource",
      "ScenarioGetTimePlayed",
      "ScenarioCreatePosition",
      "ScenarioFindBuildingProto",
      "ScenarioFindBuildingProtoForCharacter",
      "ScenarioFindPosition",
      "ScenarioSetYearsPerRound",
      "GetScenario",
      "ScenarioCreateCart",
      "ScenarioGetUnspawnedEnemiesCount",
      "ScenarioGetYearsPerRound",
      "ScenarioStopUsingOutdoorScrollBoundaries",
      "ScenarioSetOutdoorScrollBoundaries",
      "ScenarioGetDifficulty",
      "ScenarioPauseAI",
      "IsMultiplayerGame",
      "PlayerCreate",
      "DynastyCreate",
      "BossCreate",
      "FindNearestBuilding",
      "CourtingGetMaxCourtingId",
      "CourtingId2Measure",
      "MeasureCreate",
      "MeasureAddAlias",
      "MeasureAddData",
      "MeasureStart",
      "MeasureRun",
      "MeasureIsValid",
      "MeasureGetID",
      "CanBeInterruptetBy",
      "GetGametime",
      "GetSeason",
      "GetRound",
      "GetYear",
      "SetTime",
      "Gametime2Realtime",
      "Gametime2Total",
      "Realtime2Gametime",
      "SystemGetMeasurePriority",
      "SystemGetMeasureName",
      "GetFleePosition",
      "GetEvadePosition",
      "CMoveTo",
      "CMoveToWeak",
      "MoveStop",
      "MoveSetActivity",
      "MoveSetStance",
      "MoveGetStance",
      "MoveGetPrefPattern",
      "CFollow",
      "StopFollow",
      "CFight",
      "SatisfyNeed",
      "SimGetNeed",
      "SimResumePreFightMeasure",
      "ClearMeasureCache",
      "StartProduction",
      "StopProduction",
      "GetLocatorByName",
      "LocatorStatus",
      "GetFreeLocatorByName",
      "CPlayAnimation",
      "CChangeAnimation",
      "StopAnimation",
      "StopAllAnimations",
      "CLoopAnimation",
      "GetAnimationLength",
      "Fire",
      "BlockLocator",
      "ReleaseLocator",
      "CUseLocator",
      "LocatorGetBlocker",
      "GetLocatorIndex",
      "CarryObject",
      "HideObject",
      "ShowObject",
      "CExitCurrentBuilding",
      "ExitCurrentVehicle",
      "EnterVehicle",
      "Kill",
      "InternalDie",
      "InternalRemove",
      "CStroll",
      "AlignTo",
      "AlignToNearest",
      "Evacuate",
      "BuildingRallyWorkers",
      "ChangeResidence",
      "GetOutdoorMovePosition",
      "CheckSkill",
      "SetSkillValue",
      "GetSkillValue",
      "IncrementSkillValue",
      "Talk",
      "QuestTalk",
      "IsDynastySim",
      "IsPartyMember",
      "IsOnlyPartyMember",
      "SetProcessProgress",
      "SetProcessMaxProgress",
      "ResetProcessProgress",
      "SimGetHandsel",
      "SimGetWage",
      "SimIsInside",
      "SimSetClass",
      "SimGetClass",
      "SimGetGender",
      "TradeMemoryEvents",
      "CIncrementXP",
      "GetSimType",
      "SimGetLevel",
      "SimCreate",
      "SimCanBeHired",
      "SimHire",
      "SimIsMortal",
      "SimSetMortal",
      "SimSetHireable",
      "SimHasAbility",
      "SimIsWorkingTime",
      "GetName",
      "SimGetProfession",
      "SimGetWorkingPlace",
      "SimGetAssignedAreaID",
      "SimGetAssignedArea",
      "SimGetWorkingPlaceID",
      "GetFavor",
      "GetFavorToSim",
      "GetFavorToDynasty",
      "ModifyFavorToSim",
      "ModifyFavorToDynasty",
      "SetFavorToSim",
      "SetFavorToDynasty",
      "SimGetBestEvidence",
      "SimMarry",
      "SimGetBeloved",
      "SimGetSpouse",
      "SimGetDeadSpouseCount",
      "SimGetChildren",
      "SimGetChildrenCount",
      "SimCanStartCourtLover",
      "SimSetCourtLover",
      "SimGetCourtLover",
      "SimGetCourtingSim",
      "SimIsCourting",
      "SimGetLiaison",
      "SimDoCourtingAction",
      "SimAddCourtingProgress",
      "SimGetFather",
      "SimGetMother",
      "SimGetChildCount",
      "SimGetChild",
      "SimGetAlignment",
      "SimPauseWorking",
      "SimSetBehavior",
      "SimGetBehavior",
      "SimStartIdleMeasure",
      "SimResetBehavior",
      "SimSetBehaviorDataFloat",
      "SimSetBehaviorDataAlias",
      "SimLock",
      "SimSetFamily",
      "SimSetFirstname",
      "SimSetLastname",
      "SimGetLastname",
      "SimGetWealth",
      "SimCreateCompanion",
      "SimSetParents",
      "SetInvisible",
      "SimSetProduceItemID",
      "SimGetProduceItemID",
      "SimGetAge",
      "SimSetAge",
      "SimGetProductivity",
      "SimGetPregnant",
      "SimGetProgress",
      "SimSetProgress",
      "SimGetFavourableCourtingAction",
      "SimBeamMeUp",
      "SimStopMeasure",
      "EvidenceGetSeverity",
      "EvidenceGetActor",
      "SimConsumeGoods",
      "SimGetRank",
      "SimArrangeLiaison",
      "SimChargeCharacter",
      "SimAddDate",
      "SimAddDatebookEntry",
      "SimGetReligion",
      "SimGetChurch",
      "SimSetReligion",
      "SimGetFaith",
      "SimSetFaith",
      "SimReleaseCourtLover",
      "CalculateCourtingDifficulty",
      "BuildingGetInsideSimList",
      "SimCanWorkHere",
      "BuildingFindSimByName",
      "BuildingFindSimByProperty",
      "BuildingInternalLevelUp",
      "BuildingCanLevelUp",
      "BuildingFindWaterPos",
      "GetDynastyID",
      "GetDynasty",
      "GetAccessPriceTake",
      "GetAccessPriceGive",
      "GetInventory",
      "SimGetServantDynasty",
      "SimGetServantDynastyId",
      "BuildingHasUpgrade",
      "BuildingGetMaxWorkerCount",
      "BuildingGetWorkerCount",
      "BuildingGetWorker",
      "BuildingGetSimCount",
      "BuildingGetSim",
      "BuildingGetFlag",
      "BuildingSetFlagColor",
      "BuildingSetWaterPos",
      "BuildingGetWaterPos",
      "BuildingGetPrisoner",
      "BuildingGetNPC",
      "BuildingGetProfession",
      "DoNewBornStuff",
      "BuildingBuy",
      "BuildingBuyCart",
      "BuildingCanBeOwnedBy",
      "BuildingGetProto",
      "BuildingGetWorkingStart",
      "BuildingGetWorkingEnd",
      "BuildingGetFixedCosts",
      "BuildingGetFreeBudget",
      "GetBuildingBasePrice",
      "BuildingGetBuyPrice",
      "BuildingGetValue",
      "BuildingGetPriceProto",
      "BuildingGetRepairPrice",
      "BuildingGetBaseHP",
      "BuildingCanBeEntered",
      "BuildingHasIndoor",
      "BuildingCanHireNewWorker",
      "BuildingGetProducerCount",
      "BuildingGetClass",
      "BuildingGetCharacterClass",
      "BuildingGetType",
      "BuildingGetLevel",
      "BuildingGetOwner",
      "BuildingSetOwner",
      "BuildingSetForSale",
      "BuildingGetForSale",
      "BuildingGetCity",
      "BuildingGetReligion",
      "FindWorker",
      "HireWorker",
      "BuildingGetCartCount",
      "BuildingGetCart",
      "IsLocatorFree",
      "Name2BuildingType",
      "BuildingLevelMeUp",
      "BuildingCanProduce",
      "BuildingGetAISetting",
      "RoomGetInsideSimList",
      "ShowBuildingFlags",
      "BuildingIsWorkingTime",
      "CommandStructure",
      "VehicleGetModelName",
      "VehicleChangeModel",
      "BankSetCreditOffer",
      "BankGetOffer",
      "CreditGetSum",
      "CreditGetTotal",
      "CreditGetInterest",
      "CreditGetRuntime",
      "CreditGetRemainingTime",
      "GetMoney",
      "SpendMoney",
      "CreditMoney",
      "SetEndlessMoney",
      "DynastyGetMemberCount",
      "DynastyGetMember",
      "DynastyGetFamilyMemberCount",
      "DynastyGetFamilyMember",
      "DynastyGetMemberRandom",
      "DynastyGetHomeCity",
      "DynastyGetBuildingCount",
      "DynastyGetRandomBuilding",
      "DynastyFindIdleWorker",
      "DynastyGetWorkerCount",
      "DynastyGetWorker",
      "DynastyGetBuildingCount2",
      "DynastyGetBuilding2",
      "DynastyGetRandomVictim",
      "GuildGameObjects_DynastyFindTargetDynasty",
      "DynastyFindTargetDynasty",
      "DynastyGetDiplomacyState",
      "DynastyGetDiplomacyOffer",
      "DynastySetMinDiplomacyState",
      "DynastySetMaxDiplomacyState",
      "DynastyGetMinDiplomacyState",
      "DynastyGetMaxDiplomacyState",
      "DynastySetDiplomacyState",
      "DynastyMakeImpact",
      "DynastyFindNewBuilding",
      "DynastyIsPlayer",
      "DynastyIsDead",
      "DynastyGetTeam",
      "DynastyGetTotalSeaTradeValue",
      "DynastySetTeam",
      "CanBuildWorkshop",
      "GetMaxWorkshopCount",
      "DynastyIsShadow",
      "DynastyIsAI",
      "GetLocalPlayerDynasty",
      "DynastyAddMember",
      "DynastyRemoveMember",
      "DynastyTakeCredit",
      "DynastyPaybackCredit",
      "DynastyGetCredit",
      "DynastyGetRanking",
      "DynastyGetColor",
      "DynastyForceCalcDiplomacy",
      "DynastyRemoveDiplomacyStateImpact",
      "DynastyAvoidControl",
      "GetHomeBuilding",
      "SetHomeBuilding",
      "GetHomeBuildingId",
      "SetState",
      "SetStateImpact",
      "ClearStateImpact",
      "GetStateImpact",
      "GetState",
      "IsDead",
      "PlaySound",
      "PlaySoundVariation",
      "PlaySound3D",
      "PlaySound3DVariation",
      "StartHighPriorMusic",
      "ShowBoundingBox",
      "ReadyToRepeat",
      "SetRepeatTimer",
      "GetRepeatTimerLeft",
      "GetRepeatTimerEndtime",
      "SetMeasureRepeat",
      "GetMeasureRepeatName",
      "GetMeasureRepeatName2",
      "GetMeasureRepeat",
      "CreateScriptcall",
      "RemoveScriptcall",
      "CanAddItems",
      "AddItems",
      "RemoveItems",
      "RemoveEmptySlots",
      "TransferItems",
      "Transfer",
      "ThrowObject",
      "GetRemainingInventorySpace",
      "FindResourceProto",
      "ResourceFind",
      "ResourceGetLevel",
      "ResourceGetEntry",
      "ResourceGetItemId",
      "ResourceGetScriptFunc",
      "ResourceGetMeasureID",
      "ResourceCanBeChanged",
      "ResourceGetTypeCount",
      "ResourceGetTypeItem",
      "ResourceSow",
      "GetInsideBuilding",
      "GetInsideRoom",
      "GetInsideBuildingID",
      "CanBeControlled",
      "ObjectSetMeasureIcon",
      "ObjectClearMeasureIcon",
      "ObjectSetStateIcon",
      "ObjectClearStateIcon",
      "SetExclusiveMeasure",
      "ForbidMeasure",
      "AllowMeasure",
      "AllowAllMeasures",
      "GetHP",
      "GetHPRelative",
      "ModifyHP",
      "GetMaxHP",
      "AddImpact",
      "ImpactGetMaxTimeleft",
      "RemoveImpact",
      "GetImpactValue",
      "IsType",
      "IsTypeExact",
      "SetName",
      "FadeOutAllFE",
      "AddObjectDependendImpact",
      "RemoveAllObjectDependendImpacts",
      "GetNearestSettlement",
      "AddImpactDependendImpact",
      "RemoveAllImpactDependendImpacts",
      "ObjectSetHighlight",
      "ShowOverheadMeasureSymbol",
      "Plunder",
      "BattleJoin",
      "BattleLeave",
      "BattleFlee",
      "BattleGetNextEnemy",
      "BattleGetWeaponName",
      "BattleWeaponPresent",
      "BattleWeaponStore",
      "BattleIsFighting",
      "GetArmor",
      "GetDirectionTo",
      "GetRotationTo",
      "GetNobilityTitle",
      "GetNobilityTitleLabel",
      "SetNobilityTitle",
      "SimGetDivorced",
      "SimSetDoctorTitle",
      "SimGetWeaponDamage",
      "SetAvoidanceRange",
      "SetActiveAvoidance",
      "SetPassiveAvoidance",
      "SetAvoidanceGroup",
      "ReleaseAvoidanceGroup",
      "GetRadius",
      "GetVehicle",
      "SetContext",
      "SetDestroyed",
      "CopyAlias",
      "GetPosition",
      "GetPositionOfSubobject",
      "SetPosition",
      "PositionModify",
      "PositionGetArea",
      "PositionSetArea",
      "PositionGetVector",
      "PositionGetRotation",
      "PositionSetVector",
      "Position2GuildObject",
      "PositionMove",
      "GetWorldPositionXYZ",
      "GetPositionXYZ",
      "GetDistance",
      "ObjectGetRotationY",
      "GetRotation",
      "GetSettlement",
      "GetSettlementID",
      "CityGetRandomBuilding",
      "CityGetNearestBuilding",
      "CityGetBuildingCount",
      "CityGetBuildings",
      "CityGetBuildingForCharacter",
      "CityGetBuildingCountForCharacter",
      "CityGetBuildingByName",
      "CityGetServantCount",
      "CityGetServant",
      "CityBuildNewBuilding",
      "CityGetCitizenCount",
      "CityGetCrimeRate",
      "CityModifyCrimeRate",
      "CityGetLevel",
      "CitySetMaxWorkerhutLevel",
      "CitySetFixedPrice",
      "CityGetMaxWorkerhutLevel",
      "CityGuardScan",
      "CityGetWantedTime",
      "CityGetPenalty",
      "CityLevel2Label",
      "CitySimBreakout",
      "CityScheduleCutsceneEvent",
      "CityAssignTrialRoles",
      "CityAddPenalty",
      "CityGetNumEvents",
      "CityGetEventText",
      "CityGetDynastyCharList",
      "SimCanBeCharged",
      "CityFindCrowdedPlace",
      "CityFindSquad",
      "CityGetLocalMarket",
      "CityIsKontor",
      "CityGetSeller",
      "PenaltyFinish",
      "PenaltyGetPrisonTime",
      "PenaltyGetType",
      "PenaltyReset",
      "PenaltyGetOffender",
      "SettlementEventGetTime",
      "Attach3DSound",
      "Detach3DSound",
      "CartGetOperator",
      "CartCreateEscort",
      "CartRemoveEscort",
      "CartCheckEscort",
      "CartCheckFighting",
      "CartGetEscortCount",
      "CartGetType",
      "ItemGetName",
      "ItemGetSlot",
      "ItemGetProductionTime",
      "ItemGetProductionAmount",
      "ItemGetBasePrice",
      "ItemGetPriceBuy",
      "ItemGetPriceSell",
      "ItemGetSubstLevel",
      "ItemGetLabel",
      "ItemGetID",
      "ItemGetType",
      "ItemGetCategory",
      "GetItemCount",
      "IsInLoadingRange",
      "StartSingleShotParticle",
      "CommitAction",
      "StopAction",
      "ActionLock",
      "ActionIsEvidence",
      "ActionIsStopped",
      "InventoryGetSlotCount",
      "InventoryGetSlotSize",
      "InventoryGetSlotInfo",
      "FadeOutFE",
      "FadeInFE",
      "PlayFE",
      "BaseFE",
      "SetAppearance",
      "StartEmote",
      "StopEmote",
      "GetEvidenceAlignmentSum",
      "GetEvidenceValues",
      "RemoveEvidences",
      "SimGetCrimeList",
      "CrimeForfeit",
      "CrimeGetEvidenceValue",
      "ListCrimeReport",
      "GetHoursToNextTrial",
      "CampaignExit",
      "CheckPlayerExtinct",
      "CheckPlayerBankrupt",
      "SetQuestDestination",
      "NotifyOnStateChange",
      "SetQuestSource",
      "BindQuest",
      "StartQuest",
      "StartMission",
      "ResetQuest",
      "KillQuest",
      "SetQuestTitle",
      "SetQuestDescription",
      "SetQuestDescriptionByQuestname",
      "HasRunningQuest",
      "SetMainQuest",
      "SetMainQuestTitle",
      "SetMainQuestDescription",
      "EndCutscene",
      "BuildingLockForCutscene",
      "CutsceneAddEvent",
      "CutsceneCallScheduled",
      "CutsceneCallUnscheduled",
      "CutsceneCallThread",
      "CutsceneCollectEvidences",
      "AddEvidence",
      "CutsceneSetData",
      "CutsceneGetData",
      "CutsceneSendEventTrigger",
      "CutsceneAddTriggerEvent",
      "CreateCutscene",
      "CopyAliasToCutscene",
      "CopyAliasFromCutscene",
      "SimGetCutscene",
      "ListAllCutscenes",
      "BuildingGetCutscene",
      "ProfessionGetLabel",
      "AIExecutePlan",
      "AICheckWorkingPlace",
      "AIFindGoodClass",
      "GetCrimeLocation",
      "GfxAttachObject",
      "GfxDetachObject",
      "GfxStartParticle",
      "AttachModel",
      "DynastyGetFlagNumber",
      "ScenarioSetNameLanguage",
      "BlackBoardAddPamphlet",
      "BlackBoardRemovePamphlet",
      "Mount",
      "Unmount",
      "IsMount",
      "IsMounted",
      "GetMount",
      "BuildingGetRoom",
      "GetRandomPlayerDynasty",
      "ScenarioGetBuildingCount",
      "RoomLockForCutscene",
      "IncrementXPQuiet",

      // Gamebase
      "SetProperty",
      "GetProperty",
      "HasProperty",
      "ListNew",
      "ListAdd",
      "ListMerge",
      "ListRemove",
      "ListClear",
      "ListSize",
      "ListGetElement",
      "ListContains",
      "RemoveProperty",
      "Find",
      "FindByID",
      "FindByName",
      "CSendCommand",
      "BlockChar",
      "CWaitForSelection",
      "StopMeasure",
      "StopScheduledScript",
      "MsgDebugMeasure",
      "ChangeAlias",
      "RemoveAlias",
      "AliasExists",
      "SetData",
      "RemoveData",
      "GetData",
      "HasData",
      "GetDatabaseValue",
      "SetInit",
      "IsInit",
      "SetReady",
      "IsReady",
      "SetDestroyed",
      "IsDestroyed",
      "IsAIDriven",
      "IsGUIDriven",
      "IsStateDriven",
      "CShowPanel",
      "SetMouseCursorTexture",
      "ResetMouseCursorTexture",
      "Rand",
      "GFXRand",
      "GetAliasByID",
      "GetID",
      "CalcDistance",
      "MeasureSetPriority",
      "MeasureGetPriority",
      "MeasureSetNotRestartable",
      "MeasureClearRuntimeData",
      "GfxStopParticle",
      "GfxAttachObjectByID",
      "GfxSetPosition",
      "GfxDropToFloor",
      "GfxSetPositionTo",
      "GfxSetRotation",
      "GfxSetRotationTo",
      "GfxMoveNoWait",
      "GfxMoveToPositionNoWait",
      "GfxMoveToNoWait",
      "GfxRotateNoWait",
      "GfxRotateToAngleNoWait",
      "GfxRotateToNoWait",
      "GfxGetHeight",
      "GfxDetachAllObjects",
      "GfxScale",
      "GfxIsMoving",
      "GetSettingString",
      "GetSettingNumber",
      "GetCurrentMeasureName",
      "GetCurrentMeasureID",
      "GetCurrentMeasurePriority",
      "MeasureSetStopMode",

      // base
      "Include",
      "Sleep",
      "WaitForMessage",
      "Stop",
      "FindNode",
      "Cast",
      "GetValueInt",
      "GetValueFloat",
      "GetValueString",
      "LogWarning",
      "LogError",
      "LogMessage",
      "Assert",
      "LuaType",

      // Guild2ScriptBinding
      "CutsceneHUDShow",
      "CMsgQuest",
      "CMsgQuestIntro",
      "CMsgBox",
      "ChangeAppearance",
      "ShowMap",
      "ExitBuildingWithCamera",
      "HudGetActiveCharacter",
      "GetOutdoorLocator",
      "GetCameraPosition",
      "PlayerMeasureStarted",
      "HudGetActiveSheet",
      "MapHighlightObject",
      "HudSelect",
      "HudDeselect",
      "HudClearSelection",
      "HudAddToSelection",
      "HudGetSelected",
      "HudEnableElement",
      "StartMagicalEffect",
      "HudSetViewToObject",
      "HudPanelIsVisible",
      "IsDemo",
      "HudCancelUserSelection",
      "CHudRemoveCountdown",
      "TrialHUDSetSims",
      "TrialHUDSetStatus",
      "OfficeApplicationHUDSetCandidates",
      "OfficeApplicationHUDAddVoter",
      "OfficeDepositionHUDSetCandidate",
      "OfficeDepositionHUDAddVoter",
      "CInitData",
      "CInitAlias",
      "OSHSetMeasureRuntime",
      "OSHSetMeasureRepeat",
      "OSHSetMeasureCost",
      "CShowTutorialBox",
      "HideTutorialBox",
      "SetImportantPersonToSection",
      "ClearImportantPersonSection",
      "CreateImportantPersonSection",
      "ShowStatistics",
      "ResetGamespeed",
      "CutsceneShowCharacterPanel",
      "HudGetSelectionCount",

      // weather
      "Weather_SetWeather",
      "Weather_SetLight",
      "Weather_SetParticles",
      "Weather_SetCloudFactor",
      "Weather_SetWind",
      "Weather_Rand",
      "Weather_PlaySound",
      "Weather_SetSoundLoop",
      "Weather_GetValue",
      "Weather_GetSeason",

      // tolua
      "PT_ITEM",
      "PT_MEASURE",
      "EN_POSTYPE_NONE",
      "EN_POSTYPE_GROUND",
      "EN_POSTYPE_WATER",
      "EN_POSTYPE_BOTH",
      "BM_NORMAL",
      "BM_CAPTURE",
      "BM_STARTUP",
      "TRANSFER_RESULT_UNKNOWN",
      "TRANSFER_SUCCESS",
      "TRANSFER_ERROR_ILLEGAL",
      "TRANSFER_ERROR_NO_MARKET",
      "TRANSFER_ERROR_ILLEGAL_ITEM",
      "TRANSFER_ERROR_OUT_OF_RANGE",
      "TRANSFER_ERROR_ILLEGAL_EXECUTER",
      "TRANSFER_ERROR_NO_ITEM_AT_SOURCE",
      "TRANSFER_ERROR_NO_SPACE_AT_DEST",
      "TRANSFER_ERROR_ACCESS_DENIED",
      "TRANSFER_ERROR_NOT_COMPLETE_TRANSFER",
      "TRANSFER_ERROR_NOT_ENOUGH_MONEY",
      "TRANSFER_ERROR_INVALID_ITEM",
      "FILTER_IS_BUYABLE",
      "FILTER_ISNOT_BUYABLE",
      "FILTER_IGNORE",
      "FILTER_NO_DYNASTY",
      "FILTER_HAS_DYNASTY",
      "SQUAD_UNKNOWN",
      "SQUAD_INITIALISING",
      "SQUAD_EXECUTING",
      "SQUAD_SHUTDOWN",
      "RELIGION_NONE",
      "RELIGION_CATHOLIC",
      "RELIGION_EVANGELIC",
      "RELIGION_PAGAN",
      "PENALTY_UNKNOWN",
      "PENALTY_PRISON",
      "PENALTY_PILLORY",
      "PENALTY_MONEY",
      "PENALTY_DEATH",
      "PENALTY_TITLE",
      "PENALTY_FUGITIVE",
      "PENALTY_LAST",
      "EN_RANK_UNDEFINED",
      "EN_RANK_DESTITUTE",
      "EN_RANK_POOR",
      "EN_RANK_MIDDLE",
      "EN_RANK_RICH",
      "EN_RANK_WEALTHY",
      "EN_SEASON_UNDEFINED",
      "EN_SEASON_SPRING",
      "EN_SEASON_SUMMER",
      "EN_SEASON_AUTUMN",
      "EN_SEASON_WINTER",
      "DIP_FOE",
      "DIP_NEUTRAL",
      "DIP_NAP",
      "DIP_ALLIANCE",
      "ITEM_CATEGORY_NOT_TRADED",
      "ITEM_CATEGORY_RESOURCE",
      "ITEM_CATEGORY_FOOD",
      "ITEM_CATEGORY_SMITHY",
      "ITEM_CATEGORY_TEXTILE",
      "ITEM_CATEGORY_ALCHEMIST",
      "ITEM_CATEGORY_HANDICRAFT",
      "ITEM_TYPE_UNDEFINED",
      "ITEM_TYPE_NOT_TRADED",
      "ITEM_TYPE_RESOURCE",
      "ITEM_TYPE_INTERSTAGEPRODUCT",
      "ITEM_TYPE_NEED",
      "ITEM_TYPE_SUPPLY",
      "ITEM_TYPE_ARTIFACT",
      "ITEM_TYPE_ANIMAL",
      "ITEM_TYPE_PRODBYMEASURE",
      "ITEM_TYPE_GATHERING",
      "ITEM_TYPE_QUESTITEM",
      "CONSTITUTION",
      "DEXTERITY",
      "CHARISMA",
      "FIGHTING",
      "CRAFTSMANSHIP",
      "SHADOW_ARTS",
      "RHETORIC",
      "EMPATHY",
      "BARGAINING",
      "SECRET_KNOWLEDGE",
      "EN_CT_SMALL",
      "EN_CT_MIDDLE",
      "EN_CT_OX",
      "EN_CT_HORSE",
      "EN_CT_FISHERBOOT",
      "EN_CT_MERCHANTMAN_SMALL",
      "EN_CT_MERCHANTMAN_BIG",
      "EN_CT_WARSHIP",
      "EN_CT_CORSAIR",
      "NOBILITY_NONE",
      "NOBILITY_UNFREIER",
      "NOBILITY_GEMEINER",
      "NOBILITY_BUERGER",
      "NOBILITY_PATRIZIER",
      "NOBILITY_EDELMANN",
      "NOBILITY_LANDGRAF",
      "NOBILITY_FREIHERR",
      "NOBILITY_DOCTOR",
      "EDULEVEL_NONE",
      "EDULEVEL_SCHOOL",
      "EDULEVEL_UNIVERSITY1",
      "EDULEVEL_UNIVERSITY2",
      "INVENTORY_STD",
      "INVENTORY_SELL",
      "INVENTORY_EQUIPMENT",
      "MUSIC_MARRIAGE",
      "MUSIC_BIRTH",
      "MUSIC_DEATH",
      "MUSIC_EXECUTION",
      "MUSIC_DUNGEON",
      "MUSIC_POSITIVE_EVENT",
      "MUSIC_NEGATIVE_EVENT",
      "MUSIC_FIGHT",
      "MUSIC_ACCUSED",
      "MUSIC_EPIDEMIC",
      "MUSIC_PARTY",
      "MUSIC_ENEMY_SHIP_PLUNDERED",
      "MUSIC_ENEMY_SHIP_SUNK_SMALL",
      "MUSIC_ENEMY_SHIP_SUNK_MED",
      "MUSIC_ENEMY_SHIP_SUNK_BIG",
      "MUSIC_SHIP_PLUNDERED",
      "MUSIC_SHIP_SUNK",

      // office
      "OfficeSetBlock",
      "OfficeGetHolderId",
      "OfficeGetHolder",
      "OfficeGetApplicantCount",
      "OfficeGetShadowApplicantCount",
      "OfficeGetLevel",
      "OfficeGetTextLabel",
      "OfficeGetAccessRights",
      "SetOfficeServants",
      "GetOfficeTypeHolder",
      "SetOfficePrivileges",
      "OfficeGetChargeCost",
      "OfficePrepareSessionMembers",
      "OfficeRemoveApplicant",
      "OfficeGetIdx",
      "GetOfficeByApplicant",
      "SimApplyDeposition",
      "SimRunForAnOffice",
      "SimIsAppliedForOffice",
      "SimGetCityOfOffice",
      "SimSetOffice",
      "SimGetMaxOfficeLevel",
      "SimGetOfficeLevel",
      "SimGetOfficeIndex",
      "SimGetOfficeID",
      "SimGetOffice",
      "SettlementGetOfficeHolder",
      "SettlementGetOffice",
      "SettlementGetOfficeLevelCnt",
      "SettlementGetOfficeCnt",
      "CityGetHighestOfficeLevel",
      "CityGetOfficeCountAtLevel",
      "CityGetOffice",
      "CitySetOfficeApplicant",
      "CityEndOfficeElection",
      "CityRemoveFromOffice",
      "CityRemoveApplicant",
      "CityGetOfficeSessionMemberList",
      "CityGetChairmanList",
      "CityPrepareOfficesToVote",

      // db_gl
      "GL_GENDER_FEMALE",
      "GL_GENDER_MALE",
      "EN_ACTIVE",
      "EN_PASSIVE",
      "EN_BOTH",
      "GL_MEASUREDISABLE_ACTIVE",
      "GL_MEASUREDISABLE_PASSIVE",
      "GL_MEASUREDISABLE_BOTH",
      "GL_CLASS_NONE",
      "GL_CLASS_PATRON",
      "GL_CLASS_ARTISAN",
      "GL_CLASS_SCHOLAR",
      "GL_CLASS_CHISELER",
      "GL_CLASS_NPC",
      "GL_BUILDING_CLASS_LIVINGROOM",
      "GL_BUILDING_CLASS_WORKSHOP",
      "GL_BUILDING_CLASS_PUBLICBUILDING",
      "GL_BUILDING_CLASS_WORKERPOOL",
      "GL_BUILDING_CLASS_MARKET",
      "GL_BUILDING_CLASS_RESOURCE",
      "GL_BUILDING_CLASS_MILITARY",
      "GL_BUILDING_CLASS_ADDON",
      "GL_STANCE_STAND",
      "GL_STANCE_SIT",
      "GL_STANCE_LAY",
      "GL_STANCE_CROUCH",
      "GL_STANCE_KNEEL",
      "GL_STANCE_LAYGROUND",
      "GL_STANCE_SITGROUND",
      "GL_STANCE_SITBENCH",
      "GL_MOVESPEED_SNEAK",
      "GL_MOVESPEED_WALK",
      "GL_MOVESPEED_RUN",
      "GL_MOVERESULT_TARGET_REACHED",
      "GL_MOVERESULT_FOLLOW_IDLE",
      "GL_MOVERESULT_ERROR_UNKNOWN",
      "GL_MOVERESULT_ERROR_NOT_ENTERABLE_ILLEGAL_DEST",
      "GL_MOVERESULT_ERROR_NOT_ENTERABLE",
      "GL_MOVERESULT_ERROR_TARGET_GONE",
      "GL_MOVERESULT_ERROR_SELF_GONE",
      "GL_MOVERESULT_ERROR_TARGET_INACCESSIBLE",
      "GL_MOVERESULT_ERROR_TRANSITION_FAILED",
      "GL_MOVERESULT_ERROR_MOVEMENT_ABORTED",
      "GL_MOVERESULT_ERROR_TARGET_UNREACHABLE",
      "GL_MOVERESULT_ERROR_NOT_INITIALIZED",
      "GL_MOVERESULT_ERROR_UNKNOWN_PATHFINDER",
      "GL_FIGHT_HIT_TYPE_BLUNT",
      "GL_FIGHT_HIT_TYPE_SHARP",
      "GL_FIGHT_HIT_TYPE_UNARMED",
      "GL_FIGHT_HIT_TYPE_PROJECTILE",
      "GL_FIGHT_HIT_TYPE_PISTOLE",
      "GL_FIGHT_HIT_TYPE_BOMB",
      "GL_UPGRADE_TYPE_INTERIOR",
      "GL_UPGRADE_TYPE_ROOM",
      "GL_UPGRADE_TYPE_EXTERIOR",
      "GL_SCAFFOLDHEIGHT",
      "GL_SCAFFOLDSCALE",
      "GL_LOADING_DISTANCE",
      "GL_WAGE_PER_YEAR",
      "GL_RATE_FACTOR",
      "GL_WAREHOUSE_MAX_DISTANCE_HARBOR",
      "GL_COST_FOR_ESCORTGUY",
      "GL_BUILDING_TYPE_WORKER_HOUSING",
      "GL_BUILDING_TYPE_RESIDENCE",
      "GL_BUILDING_TYPE_FARM",
      "GL_BUILDING_TYPE_TAVERN",
      "GL_BUILDING_TYPE_BUTCHERY",
      "GL_BUILDING_TYPE_BAKERY",
      "GL_BUILDING_TYPE_SMITHY",
      "GL_BUILDING_TYPE_JOINERY",
      "GL_BUILDING_TYPE_TAILORING",
      "GL_BUILDING_TYPE_STONEMASON",
      "GL_BUILDING_TYPE_PIRATESNEST",
      "GL_BUILDING_TYPE_MINE",
      "GL_BUILDING_TYPE_HARBOR",
      "GL_BUILDING_TYPE_MARKET",
      "GL_BUILDING_TYPE_HERBALIST",
      "GL_BUILDING_TYPE_ALCHEMIST",
      "GL_BUILDING_TYPE_ARTISAN",
      "GL_BUILDING_TYPE_RANGERHUT",
      "GL_BUILDING_TYPE_CHURCH_EV",
      "GL_BUILDING_TYPE_CHURCH_CATH",
      "GL_BUILDING_TYPE_MERCENARY",
      "GL_BUILDING_TYPE_DESTILLERY",
      "GL_BUILDING_TYPE_TOWNHALL",
      "GL_BUILDING_TYPE_WELL",
      "GL_BUILDING_TYPE_PRISON",
      "GL_BUILDING_TYPE_GUILDHOUSE",
      "GL_BUILDING_TYPE_ARSENAL",
      "GL_BUILDING_TYPE_EXECUTIONS_PLACE",
      "GL_BUILDING_TYPE_GRAVEYARD",
      "GL_BUILDING_TYPE_RESOURCE",
      "GL_BUILDING_TYPE_DUELPLACE",
      "GL_BUILDING_TYPE_LINGERPLACE",
      "GL_BUILDING_TYPE_BUILDABLERESOURCE",
      "GL_BUILDING_TYPE_KONTOR",
      "GL_BUILDING_TYPE_FISHINGHUT",
      "GL_BUILDING_TYPE_DIVEHOUSE",
      "GL_BUILDING_TYPE_HOSPITAL",
      "GL_BUILDING_TYPE_WAREHOUSE",
      "GL_BUILDING_TYPE_WATERRESOURCE",
      "GL_BUILDING_TYPE_TOWER",
      "GL_BUILDING_TYPE_BLACKBOARD",
      "GL_BUILDING_TYPE_WEDDINGCHAPEL",
      "GL_BUILDING_TYPE_BANKHOUSE",
      "GL_BUILDING_TYPE_NEKRO",
      "GL_BUILDING_TYPE_ROBBER",
      "GL_BUILDING_TYPE_THIEF",
      "GL_BUILDING_TYPE_JUGGLER",
      "GL_BUILDING_TYPE_MILL",
      "GL_BUILDING_TYPE_FRUITFARM",
      "GL_BUILDING_TYPE_SOLDIERPLACE",
      "GL_BUILDING_TYPE_ESTATE",
      "GL_PROFESSION_PEASANT",
      "GL_PROFESSION_BREWER",
      "GL_PROFESSION_BUTCHER",
      "GL_PROFESSION_BAKER",
      "GL_PROFESSION_BLACKSMITH",
      "GL_PROFESSION_JOINER",
      "GL_PROFESSION_TAILOR",
      "GL_PROFESSION_HUNTER",
      "GL_PROFESSION_ALCHIMIST",
      "GL_PROFESSION_TOWNCRIER",
      "GL_PROFESSION_PRIEST",
      "GL_PROFESSION_HERBALIST",
      "GL_PROFESSION_MINER",
      "GL_PROFESSION_ARTISAN",
      "GL_PROFESSION_ROBBER",
      "GL_PROFESSION_LUMBERJACK",
      "GL_PROFESSION_MERCENARY",
      "GL_PROFESSION_MYRMIDON",
      "GL_PROFESSION_DYNASTYCHAR",
      "GL_PROFESSION_CARTOPERATOR",
      "GL_PROFESSION_CITYGUARD",
      "GL_PROFESSION_PRISONGUARD",
      "GL_PROFESSION_INSPECTOR",
      "GL_PROFESSION_MONITOR",
      "GL_PROFESSION_ELITEGUARD",
      "GL_PROFESSION_THIEF",
      "GL_PROFESSION_INQUISITOR",
      "GL_PROFESSION_FISHER",
      "GL_PROFESSION_COCOTTE",
      "GL_PROFESSION_MEDIC",
      "GL_PROFESSION_MUSICIAN",
      "GL_PROFESSION_USHER",
      "GL_PROFESSION_TOWNHALLGUARD",
      "GL_PROFESSION_EXECUTIONER",
      "GL_PROFESSION_SECOND",
      "GL_PROFESSION_VENDOR",
      "GL_PROFESSION_UNDERTAKER",
      "GL_PROFESSION_NONE",
      "GL_PROFESSION_NEKRO",
      "GL_PROFESSION_BANKIER",
      "GL_PROFESSION_JUGGLER",
      "GL_PROFESSION_DOG",
      "GL_PROFESSION_CAT",
      "GL_PROFESSION_CHICKEN",
      "GL_PROFESSION_COCK",
      "GL_PROFESSION_DUCK",
      "GL_PROFESSION_GOOSE",
      "GL_PROFESSION_WOLF",
      "GL_PROFESSION_DEER_F",
      "GL_PROFESSION_DEER_M",
      "GL_PROFESSION_SHEEP",
      "GL_PROFESSION_COW",
      "GL_PROFESSION_PIG",
      "GL_PROFESSION_STONEMASONER",
      "GL_PROFESSION_RATBOY",
      "GL_PROFESSION_MILLER",
      "GL_PROFESSION_DISTILLER",
      "GL_PROFESSION_ORCHARDIST",
      "GL_PROFESSION_PRIVATEGUARD",
      "GL_PROFESSION_DIPLOMAT",
      "EN_RECOVERFACTOR_HOME",
      "EN_RECOVERFACTOR_TAVERN",
      "EN_RECOVERFACTOR_WILDERNESS",
      "GL_MAX_CITY_LEVEL",
      "GL_HIGHEST_NOBILITY_TITLE",
      "GL_EXP_GAIN_SIMPLE",
      "GL_EXP_GAIN_COMMON",
      "GL_EXP_GAIN_SCALING",
      "GL_EXP_GAIN_RARE",
      "GL_EXP_GAIN_HIGH_RISK",
      "GL_EXP_GAIN_LIFETIME",
      "GL_IMPACT_TALENT_VALUE_TINY",
      "GL_IMPACT_TALENT_VALUE_SMALL",
      "GL_IMPACT_TALENT_VALUE_MEDIUM",
      "GL_IMPACT_TALENT_VALUE_GREAT",
      "GL_IMPACT_TALENT_VALUE_EPIC",
      "GL_IMPACT_DURATION_VERY_SHORT",
      "GL_IMPACT_DURATION_SHORT",
      "GL_IMPACT_DURATION_MEDIUM",
      "GL_IMPACT_DURATION_LONG",
      "GL_IMPACT_DURATION_EPIC",
      "GL_DURATION_OF_THREAT_EFFECT",
      "GL_PERCENT_FAVOR_LOSS_AFTER_THREAT",
      "GL_EVIDENCE_SUM_LOW_THREAT_SUCCESS",
      "GL_EVIDENCE_SUM_MIDDLE_THREAT_SUCCESS",
      "GL_EVIDENCE_SUM_HIGH_THREAT_SUCCESS",
      "GL_DURATION_OF_THREAT_EFFECT_LOW_SUCCESS",
      "GL_DURATION_OF_THREAT_EFFECT_HIGH_SUCCESS",
      "GL_PERCENT_FAVOR_LOSS_AFTER_DIVORCE",
      "GL_SCHOOLMONEY",
      "GL_APPRENTICESHIPMONEY",
      "GL_UNIVERSITYMONEY",
      "GL_SCHOOLTIME",
      "GL_APPRENTICESHIPTIME",
      "GL_STUDYTIME_FIRST",
      "GL_STUDYTIME_SECOND",
      "GL_AGE_FOR_APPRENTICESHIP",
      "GL_AGE_FOR_SCHOOL",
      "GL_AGE_FOR_UNIVERSITY",
      "GL_AGE_FOR_GROWNUP",
      "GL_TIME_LYING_DEAD_ON_THE_GROUND",
      "GL_TIME_TO_REPAIR_ONE_CART_HP",
      "GL_TRAINING_SESSION_DURATION",
      "GL_AI_WAIT_FOR_COURTING_PLAYER",
      "GL_COURT_LOVER_MINFAVOR",
      "GL_MAX_CRUSADERS",
      "GL_IMPERIAL_FAME_POINTS_KNOWN",
      "GL_IMPERIAL_FAME_POINTS_NOTED",
      "GL_IMPERIAL_FAME_POINTS_RESPECTED",
      "GL_IMPERIAL_FAME_POINTS_LIKED",
      "GL_IMPERIAL_FAME_POINTS_FAMOUS",
      "GL_IMPERIAL_FAME_INCREMENT_SCHOOL",
      "GL_FAME_POINTS_KNOWN",
      "GL_FAME_POINTS_NOTED",
      "GL_FAME_POINTS_RESPECTED",
      "GL_FAME_POINTS_LIKED",
      "GL_FAME_POINTS_FAMOUS",
      "GL_FAME_INCREMENT_SCHOOL",
      "GL_SKILLCHECK_EASY",
      "GL_SKILLCHECK_MEDIUM",
      "GL_SKILLCHECK_HARD",
      "GL_SKILLCHECK_IMPOSSIBLE",
      "GL_GRUDGES_MAX",
      "GL_FONDNESS_MAX",
      "GL_FAVOR_MOD_TINY",
      "GL_FAVOR_MOD_VERYSMALL",
      "GL_FAVOR_MOD_SMALL",
      "GL_FAVOR_MOD_NORMAL",
      "GL_FAVOR_MOD_GREATER",
      "GL_FAVOR_MOD_LARGE",
      "GL_FAVOR_MOD_VERYLARGE",
      "GL_FAVOR_MOD_EPIC",
      "GL_FAVOR_MOD_MAX",
      "GL_STARTUP_XP_SHADOW_DYNASTY",
      "GL_MAX_CHILD_COUNT",
      "GL_BASE_PRICE_ADOPTORPHAN",
      "GL_TRIAL_COST_BASE",
      "GL_TRIAL_COST_PER_LEVEL",
      "GL_TRIAL_PENALTY_LOW",
      "GL_TRIAL_PENALTY_MEDIUM",
      "GL_TRIAL_PENALTY_HIGH",
      "GL_COMPLIMENT_MINFAVOR",
      "GL_STARTDIALOG_MINFAVOR",
      "GL_FLIRT_MINFAVOR",
      "GL_HUG_MINFAVOR",
      "GL_PRESENT_MINFAVOR",
      "GL_KISS_MINFAVOR",
      "GL_DANCE_MINFAVOR",
      "GL_BEWITCH_MINFAVOR",
      "GL_BATH_MINFAVOR",
      "GL_DANCING_COST",
      "GL_BATH_ALONE_COST",
      "GL_BATH_TOGETHER_COST",
      "GL_BEWITCH_COST",
      "GL_RENT_SLEEPING_COST",
      "GL_MEASURE_PRIORITY_MINIMAL",
      "GL_MEASURE_PRIORITY_VERYLOW",
      "GL_MEASURE_PRIORITY_LOW",
      "GL_MEASURE_PRIORITY_NORMAL",
      "GL_MEASURE_PRIORITY_MEDIUM",
      "GL_MEASURE_PRIORITY_HIGH",
      "GL_MEASURE_PRIORITY_MAX",
      "GL_RANK_UNDEFINED",
      "GL_RANK_DESTITUTE",
      "GL_RANK_POOR",
      "GL_RANK_MIDDLE",
      "GL_RANK_RICH",
      "GL_RANK_WEALTHY",
      "GL_PROPEL_EMPLOYEES_FAVOR_LOSS",

      // building
      "StartRoomAnimation",
      "StopRoomAnimation",
      "SetRoomAnimationTime",

      // camera
      "CameraIsIndoor",
      "CameraIsTerrain",
      "CameraIsLocked",
      "CameraTerrainSet",
      "CameraFollow",
      "CameraTerrainSetPos",
      "CameraIndoorSetRoom",
      "CameraIndoorSetBuilding",
      "CameraIndoorGetRoom",
      "CameraIndoorGetBuilding",
      "CameraEnableUserUnlock",
      "CameraLock",
      "CameraLockLookAt",
      "CameraUnlock",
      "CameraBlend",
      "CameraCheckLineOfSight",
      "CutsceneCameraCreate",
      "CutsceneCameraSetAbsolutePosition",
      "CutsceneCameraSetRelativePosition",
      "CutsceneCameraBlend",
      "CutsceneCameraRelease",
      "CutsceneLocalPlayerIsWatching",
      "CutsceneAddSim",
      "CutsceneRemoveSim",
      "DestroyCutscene",
      "CutsceneSetTimeBar",
      "CutsceneSetMeasureLockTime",
      "CutsceneGetMeasureLockTime",

      // states
      "STATE_IDLE",
      "STATE_BURNING",
      "STATE_BUILDING",
      "STATE_REPAIRING",
      "STATE_LEVELINGUP",
      "STATE_DEAD",
      "STATE_SCANNING",
      "STATE_CAPTURED",
      "STATE_IMPRISONED",
      "STATE_FIGHTING",
      "STATE_CONTAMINATED",
      "STATE_UNCONSCIOUS",
      "STATE_CUTSCENE",
      "STATE_MONITORDAMAGE",
      "STATE_PREGNANT",
      "STATE_NPC",
      "STATE_LOCKED",
      "STATE_PILLORY",
      "STATE_WORKING",
      "STATE_HIJACKED",
      "STATE_CHILD",
      "STATE_DYING",
      "STATE_ROBBERGUARD",
      "STATE_REVOLT",
      "STATE_GUILDTRAVELLING",
      "STATE_INSPECTED",
      "STATE_FEAST",
      "STATE_HIDDEN",
      "STATE_DRIVERATTACKED",
      "STATE_TOWNNPC",
      "STATE_NPCFIGHTER",
      "STATE_DUEL",
      "STATE_SLEEPING",
      "STATE_ACTIVE_ESCORT",
      "STATE_SICK",
      "STATE_KONTOR_EVENT",
      "STATE_CRUSADE",
      "STATE_INVISIBLE",
      "STATE_MARINECONTROL",
      "STATE_SITAROUND",
      "STATE_TOTALLYDRUNK",
      "STATE_LOCKEDALT",
      "STATE_GUARDING",
      "STATE_JEWELLERY",
      "STATE_GUILD_EVENT",
      "STATE_DONKEYTEAM",
      "STATE_CHECKFORSPINNINGS",
      "STATE_INLOVE",
      "STATE_POISONED",
      "STATE_TRADERCONTROL",
      "STATE_HPFZ_TRAUMLAND",
      "STATE_HPFZ_HYPNOSE",
      "STATE_TWP_AUTOCART",
      "STATE_HPFZ_VERFLUCHT",
      "STATE_RIDING",
      "STATE_LUCKYGUY",
      "STATE_SELLFLAG",
      "STATE_MOVING_BUILDING",
      "STATE_GLOBAL_EVENT",
      "STATE_GLOBALTRAVELLING",
      "STATE_ANIMAL",

      // other
      "IncrementXP",
      "GfxRotateToAngle",
      "MsgNewsNoWait",
      "MsgSayNoWait",
      "PlayAnimation",
      "LoopAnimation",
      "PlayAnimationNoWait",
      "MsgSay",
      "GfxMoveToPosition",
      "InitData",
      "MsgBox",
      "MsgBoxNoWait",
      "SendCommandNoWait",
      "HudRemoveCountdown",
      "MsgNews",
      "MsgSayInteraction",
      "this",
      "ShowTutorialBoxNoWait",
      "MsgQuest",
      "InitAlias",
      "GetVariableParameters",

      "STOP_FORCE_DWORD",
      "STOP_NOMOVE",
      "STOP_NOSTOP",
      "STOP_CANCEL",
      "STOP_MEASURE",

      "MEASUREINIT_SELECTION",
      "MEASUREINIT_PANEL_CLASS",
      
      // from FUN_0056b400
      "cl_InputGameModule",
      "cl_SimCommand",
      "cl_SimObject",
      "i_AppLoop",
      "cl_ScriptSimObject",
      "cl_PropertyHolder",
      "i_SoundEngine",
      "cl_Root",
      "cl_LoadingScreen",
      "cl_MusicGameModule",
      "i_Game",
      "cl_SimWorld",
      "cl_CoreNode",
      "cl_GameModule",
      "cl_Measure",
      "cl_SimulationController",

  };

  std::map<std::string, DefinitionLocation> GlobalIndex;

  fs::path ScriptsRoot;

  std::string GeneratePrefix(const std::string &filename) {
    std::string stem = fs::path(filename).stem().string();
    std::transform(stem.begin(), stem.end(), stem.begin(), ::tolower);
    return stem + "_";
  }

public:
  void SetRoot(const fs::path &root) { ScriptsRoot = root; }

  void ScanFile(const std::string &filePath) {
    if (!fs::exists(filePath))
      return;

    std::ifstream file(filePath);
    if (!file.good()) {
      file.open(fs::current_path() / filePath);
      if (!file.good())
        return;
    }
    std::string line;
    std::string prefix = GeneratePrefix(filePath);

    // 'function Name(...)' with no whitespaces at the beginning (top-level
    // functions)
    // top-level functions in tg2 are required to not have
    // whitespaces at the beginning, so we can simplify our regex like that
    static const std::regex funcRe(R"(^function\s+([a-zA-Z0-9_]+)\s*\()");

    // Constants 'CAPS_LOCK = ...'
    static const std::regex constRe(R"(^\s*([A-Z_][A-Z0-9_]*)\s*=)");

    // 'end' for top-level functions
    static const std::regex mainEndRe(R"(^end\b)");

    std::smatch match;
    int lineNum = 0;
    bool insideMainFunction = false;

    while (std::getline(file, line)) {
      lineNum++;

      if (std::regex_search(line, match, funcRe)) {
        insideMainFunction = true;
        std::string funcName = match[1].str();
        std::string globalName = prefix + funcName;
        GlobalIndex[globalName] = {filePath, lineNum};
        continue;
      }

      if (insideMainFunction) {
        if (std::regex_search(line, mainEndRe)) {
          insideMainFunction = false;
        }
        continue;
      }

      if (!insideMainFunction) {
        if (std::regex_search(line, match, constRe)) {
          std::string varName = match[1].str();
          bool isAllCaps = true;
          bool hasAlpha = false;

          for (char c : varName) {
            if (std::isalpha(c)) {
              hasAlpha = true;
              if (!std::isupper(c)) {
                isAllCaps = false;
                break;
              }
            }
          }

          if (isAllCaps && hasAlpha) {
            GlobalIndex[varName] = {filePath, lineNum};
          }
        }
      }
    }
  }

  void ScanAll() {
    if (!fs::exists(ScriptsRoot))
      return;
    GlobalIndex.clear();

    try {
      for (const auto &entry : fs::recursive_directory_iterator(ScriptsRoot)) {
        if (entry.is_regular_file() && entry.path().extension() == ".lua") {
          std::error_code ec;
          fs::path relPath = fs::relative(entry.path(), fs::current_path(), ec);

          std::string finalPath;
          if (!ec) {
            finalPath = relPath.string();
          } else {
            finalPath = entry.path().string();
          }

          std::replace(finalPath.begin(), finalPath.end(), '\\', '/');
          ScanFile(finalPath);
        }
      }
    } catch (...) {
    }
  }

  bool FindDefinition(const std::string &query, DefinitionLocation &outLoc) {
    auto it = GlobalIndex.find(query);
    if (it != GlobalIndex.end()) {
      outLoc = it->second;
      return true;
    }

    std::string queryLower = query;
    std::transform(queryLower.begin(), queryLower.end(), queryLower.begin(),
                   ::tolower);

    for (const auto &[key, loc] : GlobalIndex) {
      std::string keyLower = key;
      std::transform(keyLower.begin(), keyLower.end(), keyLower.begin(),
                     ::tolower);
      if (keyLower == queryLower) {
        outLoc = loc;
        return true;
      }
    }

    for (const auto &[key, loc] : GlobalIndex) {
      if (key.size() > query.size() + 1) {
        if (key.substr(key.size() - query.size()) == query &&
            key[key.size() - query.size() - 1] == '_') {
          outLoc = loc;
          return true;
        }
      }
    }

    return false;
  }

  void GenerateConfig() {
    if (!fs::exists(ScriptsRoot))
      return;

    fs::path configPath = ScriptsRoot / ".luacheckrc";
    std::ofstream out(configPath);

    if (!out.good())
      return;

    out << "-- AUTOMATICALLY GENERATED BY SECONDAID\n";
    // out << "std = \"lua51\"\n\n";

    out << "read_globals = {\n";

    for (const auto &glob : StaticGlobals) {
      out << "    \"" << glob << "\",\n";
    }
    out << "}\n\n";

    out << "globals = {\n";
    // It could be done dynamically... it will suffice for now, because in mmp
    // there is only Disease class
    out << "\n    -- CLASSES --\n";
    out << "    \"Disease\",\n";

    out << "\n    -- DYNAMIC GLOBALS --\n";
    for (const auto &[name, loc] : GlobalIndex) {
      out << "    \"" << name << "\",\n";
    }
    out << "}\n\n";

    out << "ignore = "
           "{\"211\",\"212\",\"213\",\"231\",\"311\",\"312\",\"313\",\"631\","
           "\"611\",\"612\",\"613\",\"614\",\"621\",\"111\"}\n";

    out << "color = false\n";
    out << "codes = true\n";
  }
};
